/* Generated by SymPy; requires <math.h> for fabs */
template <typename T>
static inline void compute_face_vertex_tolerance_soa(
    const T codomain_tol,
    const T v0sx,
    const T v0sy,
    const T v0sz,
    const T v1sx,
    const T v1sy,
    const T v1sz,
    const T v2sx,
    const T v2sy,
    const T v2sz,
    const T v3sx,
    const T v3sy,
    const T v3sz,
    const T v0ex,
    const T v0ey,
    const T v0ez,
    const T v1ex,
    const T v1ey,
    const T v1ez,
    const T v2ex,
    const T v2ey,
    const T v2ez,
    const T v3ex,
    const T v3ey,
    const T v3ez,
    T* const SFEM_RESTRICT tol0,
    T* const SFEM_RESTRICT tol1,
    T* const SFEM_RESTRICT tol2)
{
    const T ssa0 = v0ex - v0sx;
    const T ssa1 = -v2ex;
    const T ssa2 = ssa0 + v2sx;
    const T ssa3 = -v3ex;
    const T ssa4 = ssa3 + v3sx;
    const T ssa5 = v0ey - v0sy;
    const T ssa6 = -v2ey;
    const T ssa7 = ssa5 + v2sy;
    const T ssa8 = -v3ey;
    const T ssa9 = ssa8 + v3sy;
    const T ssa10 = v0ez - v0sz;
    const T ssa11 = -v2ez;
    const T ssa12 = ssa10 + v2sz;
    const T ssa13 = -v3ez;
    const T ssa14 = ssa13 + v3sz;
    const T ssa15 = ssa1 + v1ex;
    const T ssa16 = ssa6 + v1ey;
    const T ssa17 = ssa11 + v1ez;
    const T ssa18 = (1.0 / 3.0) * codomain_tol;
    *tol0 =
        ssa18
        / sccd::max<T>(
            sccd::abs<T>(ssa0 + ssa4),
            sccd::max<T>(
                sccd::abs<T>(ssa1 + ssa2),
                sccd::max<T>(
                    sccd::abs<T>(ssa10 + ssa14),
                    sccd::max<T>(
                        sccd::abs<T>(ssa11 + ssa12),
                        sccd::max<T>(
                            sccd::abs<T>(ssa5 + ssa9),
                            sccd::max<T>(
                                sccd::abs<T>(ssa6 + ssa7),
                                sccd::max<T>(
                                    sccd::abs<T>(ssa0 - v1ex + v1sx),
                                    sccd::max<T>(
                                        sccd::abs<T>(ssa10 - v1ez + v1sz),
                                        sccd::max<T>(
                                            sccd::abs<T>(ssa5 - v1ey + v1sy),
                                            sccd::max<T>(
                                                sccd::abs<T>(
                                                    ssa12 + ssa14 + ssa17
                                                    - v1sz),
                                                sccd::max<T>(
                                                    sccd::abs<T>(
                                                        ssa15 + ssa2 + ssa4
                                                        - v1sx),
                                                    sccd::abs<T>(
                                                        ssa16 + ssa7 + ssa9
                                                        - v1sy))))))))))));
    *tol1 = ssa18
        / sccd::max<T>(
                sccd::abs<T>(ssa15),
                sccd::max<T>(
                    sccd::abs<T>(ssa16),
                    sccd::max<T>(
                        sccd::abs<T>(ssa17),
                        sccd::max<T>(
                            sccd::abs<T>(v1sx - v2sx),
                            sccd::max<T>(
                                sccd::abs<T>(v1sy - v2sy),
                                sccd::abs<T>(v1sz - v2sz))))));
    *tol2 = ssa18
        / sccd::max<T>(
                sccd::abs<T>(ssa13 + v1ez),
                sccd::max<T>(
                    sccd::abs<T>(ssa3 + v1ex),
                    sccd::max<T>(
                        sccd::abs<T>(ssa8 + v1ey),
                        sccd::max<T>(
                            sccd::abs<T>(v1sx - v3sx),
                            sccd::max<T>(
                                sccd::abs<T>(v1sy - v3sy),
                                sccd::abs<T>(v1sz - v3sz))))));
}

template <typename T>
static inline void compute_edge_edge_tolerance_soa(
    const T codomain_tol,
    const T v0sx,
    const T v0sy,
    const T v0sz,
    const T v1sx,
    const T v1sy,
    const T v1sz,
    const T v2sx,
    const T v2sy,
    const T v2sz,
    const T v3sx,
    const T v3sy,
    const T v3sz,
    const T v0ex,
    const T v0ey,
    const T v0ez,
    const T v1ex,
    const T v1ey,
    const T v1ez,
    const T v2ex,
    const T v2ey,
    const T v2ez,
    const T v3ex,
    const T v3ey,
    const T v3ez,
    T* const SFEM_RESTRICT tol0,
    T* const SFEM_RESTRICT tol1,
    T* const SFEM_RESTRICT tol2)
{
    const T ssa0 = v0ex - v0sx;
    const T ssa1 = -v2ex + v2sx;
    const T ssa2 = -v3ex + v3sx;
    const T ssa3 = v0ey - v0sy;
    const T ssa4 = -v2ey + v2sy;
    const T ssa5 = -v3ey + v3sy;
    const T ssa6 = v0ez - v0sz;
    const T ssa7 = -v2ez + v2sz;
    const T ssa8 = -v3ez + v3sz;
    const T ssa9 = -v1sx;
    const T ssa10 = ssa9 + v1ex;
    const T ssa11 = -v1sy;
    const T ssa12 = ssa11 + v1ey;
    const T ssa13 = -v1sz;
    const T ssa14 = ssa13 + v1ez;
    const T ssa15 = (1.0 / 3.0) * codomain_tol;
    const T ssa16 =
        ssa15
        / sccd::max<T>(
            sccd::abs<T>(ssa0 + ssa1),
            sccd::max<T>(
                sccd::abs<T>(ssa0 + ssa2),
                sccd::max<T>(
                    sccd::abs<T>(ssa1 + ssa10),
                    sccd::max<T>(
                        sccd::abs<T>(ssa10 + ssa2),
                        sccd::max<T>(
                            sccd::abs<T>(ssa12 + ssa4),
                            sccd::max<T>(
                                sccd::abs<T>(ssa12 + ssa5),
                                sccd::max<T>(
                                    sccd::abs<T>(ssa14 + ssa7),
                                    sccd::max<T>(
                                        sccd::abs<T>(ssa14 + ssa8),
                                        sccd::max<T>(
                                            sccd::abs<T>(ssa3 + ssa4),
                                            sccd::max<T>(
                                                sccd::abs<T>(ssa3 + ssa5),
                                                sccd::max<T>(
                                                    sccd::abs<T>(ssa6 + ssa7),
                                                    sccd::abs<T>(
                                                        ssa6 + ssa8))))))))))));
    *tol0 = ssa16;
    *tol1 = ssa16;
    *tol2 = ssa15
        / sccd::max<T>(
                sccd::abs<T>(ssa11 + v0sy),
                sccd::max<T>(
                    sccd::abs<T>(ssa13 + v0sz),
                    sccd::max<T>(
                        sccd::abs<T>(ssa9 + v0sx),
                        sccd::max<T>(
                            sccd::abs<T>(v0ex - v1ex),
                            sccd::max<T>(
                                sccd::abs<T>(v0ey - v1ey),
                                sccd::abs<T>(v0ez - v1ez))))));
}
