#ifndef SCCD_TOLERANCE_HPP
#define SCCD_TOLERANCE_HPP

/* Generated by SymPy; requires <math.h> for fabs */

// SCCD_RESTRICT is used below, so the header that defines it must be pulled in
// here rather than relying on the include order at each use site.
#include "sccd_base.hpp"
#include "sccd_math.hpp"

#include <math.h>

// TightInclusion caps the per-axis domain tolerances (ccd.cpp:
// CCD_MAX_TIME_TOL / CCD_MAX_COORD_TOL).
//
// The tolerances below are distance_tolerance divided by a rate of change, so a
// query with (near) no motion along an axis divides by ~0 and gets an
// effectively infinite tolerance: measured here, a fully static vertex-face
// query yields tol[0] = inf and a near-static one 1.0e+06. Every box then
// trivially satisfies "width <= tol", so the root box is accepted on sight and
// the query reports toi == 0.
//
// That failure is in the *conservative* direction -- an early time of impact,
// not a late one -- so it does not break the safety invariant. What it destroys
// is usefulness and speed: near-static geometry degenerates into "collision at
// t = 0" for every such query. Capping matches TightInclusion and keeps those
// queries meaningful.
#ifndef SCCD_MAX_TIME_TOL
#define SCCD_MAX_TIME_TOL 1e-3
#endif
#ifndef SCCD_MAX_COORD_TOL
#define SCCD_MAX_COORD_TOL 1e-2
#endif

SCCD_FP_STRICT_BEGIN

namespace sccd {
    /**
     * \brief Cap a domain tolerance, mirroring TightInclusion's clamp_div.
     *
     * A zero denominator upstream yields +inf here, and min() maps that to the
     * cap, which is exactly what clamp_div returns for b == 0. NaN also maps to
     * the cap, which is the conservative direction.
     */
    template <typename T>
    static inline T clamp_domain_tol(const T value, const T cap) {
        return (value < cap) ? value : cap;
    }


template <typename T>
static inline void compute_face_vertex_tolerance_soa(const T codomain_tol,
                                                     const T v0sx,
                                                     const T v0sy,
                                                     const T v0sz,
                                                     const T v1sx,
                                                     const T v1sy,
                                                     const T v1sz,
                                                     const T v2sx,
                                                     const T v2sy,
                                                     const T v2sz,
                                                     const T v3sx,
                                                     const T v3sy,
                                                     const T v3sz,
                                                     const T v0ex,
                                                     const T v0ey,
                                                     const T v0ez,
                                                     const T v1ex,
                                                     const T v1ey,
                                                     const T v1ez,
                                                     const T v2ex,
                                                     const T v2ey,
                                                     const T v2ez,
                                                     const T v3ex,
                                                     const T v3ey,
                                                     const T v3ez,
                                                     T* const SCCD_RESTRICT tol0,
                                                     T* const SCCD_RESTRICT tol1,
                                                     T* const SCCD_RESTRICT tol2) {
    const T ssa0 = v0ex - v0sx;
    const T ssa1 = -v2ex;
    const T ssa2 = ssa0 + v2sx;
    const T ssa3 = -v3ex;
    const T ssa4 = ssa3 + v3sx;
    const T ssa5 = v0ey - v0sy;
    const T ssa6 = -v2ey;
    const T ssa7 = ssa5 + v2sy;
    const T ssa8 = -v3ey;
    const T ssa9 = ssa8 + v3sy;
    const T ssa10 = v0ez - v0sz;
    const T ssa11 = -v2ez;
    const T ssa12 = ssa10 + v2sz;
    const T ssa13 = -v3ez;
    const T ssa14 = ssa13 + v3sz;
    const T ssa15 = ssa1 + v1ex;
    const T ssa16 = ssa6 + v1ey;
    const T ssa17 = ssa11 + v1ez;
    const T ssa18 = (1.0 / 3.0) * codomain_tol;
    *tol0 =
        ssa18 /
        sccd::max<T>(
            sccd::abs<T>(ssa0 + ssa4),
            sccd::max<T>(
                sccd::abs<T>(ssa1 + ssa2),
                sccd::max<T>(
                    sccd::abs<T>(ssa10 + ssa14),
                    sccd::max<T>(
                        sccd::abs<T>(ssa11 + ssa12),
                        sccd::max<T>(
                            sccd::abs<T>(ssa5 + ssa9),
                            sccd::max<T>(
                                sccd::abs<T>(ssa6 + ssa7),
                                sccd::max<T>(
                                    sccd::abs<T>(ssa0 - v1ex + v1sx),
                                    sccd::max<T>(
                                        sccd::abs<T>(ssa10 - v1ez + v1sz),
                                        sccd::max<T>(sccd::abs<T>(ssa5 - v1ey + v1sy),
                                                     sccd::max<T>(sccd::abs<T>(ssa12 + ssa14 + ssa17 - v1sz),
                                                                  sccd::max<T>(sccd::abs<T>(ssa15 + ssa2 + ssa4 - v1sx),
                                                                               sccd::abs<T>(ssa16 + ssa7 + ssa9 -
                                                                                            v1sy))))))))))));
    *tol1 = ssa18 / sccd::max<T>(sccd::abs<T>(ssa15),
                                 sccd::max<T>(sccd::abs<T>(ssa16),
                                              sccd::max<T>(sccd::abs<T>(ssa17),
                                                           sccd::max<T>(sccd::abs<T>(v1sx - v2sx),
                                                                        sccd::max<T>(sccd::abs<T>(v1sy - v2sy),
                                                                                     sccd::abs<T>(v1sz - v2sz))))));
    *tol2 = ssa18 / sccd::max<T>(sccd::abs<T>(ssa13 + v1ez),
                                 sccd::max<T>(sccd::abs<T>(ssa3 + v1ex),
                                              sccd::max<T>(sccd::abs<T>(ssa8 + v1ey),
                                                           sccd::max<T>(sccd::abs<T>(v1sx - v3sx),
                                                                        sccd::max<T>(sccd::abs<T>(v1sy - v3sy),
                                                                                     sccd::abs<T>(v1sz - v3sz))))));
    *tol0 = sccd::clamp_domain_tol<T>(*tol0, T(SCCD_MAX_TIME_TOL));
    *tol1 = sccd::clamp_domain_tol<T>(*tol1, T(SCCD_MAX_COORD_TOL));
    *tol2 = sccd::clamp_domain_tol<T>(*tol2, T(SCCD_MAX_COORD_TOL));
}

template <typename T>
static inline void compute_face_vertex_tolerance(const T codomain_tol,
                                                 const T v0s[3],
                                                 const T v1s[3],
                                                 const T v2s[3],
                                                 const T v3s[3],
                                                 const T v0e[3],
                                                 const T v1e[3],
                                                 const T v2e[3],
                                                 const T v3e[3],
                                                 T* const SCCD_RESTRICT tol) {
    compute_face_vertex_tolerance_soa<T>(codomain_tol,
                                         v0s[0],
                                         v0s[1],
                                         v0s[2],
                                         v1s[0],
                                         v1s[1],
                                         v1s[2],
                                         v2s[0],
                                         v2s[1],
                                         v2s[2],
                                         v3s[0],
                                         v3s[1],
                                         v3s[2],
                                         v0e[0],
                                         v0e[1],
                                         v0e[2],
                                         v1e[0],
                                         v1e[1],
                                         v1e[2],
                                         v2e[0],
                                         v2e[1],
                                         v2e[2],
                                         v3e[0],
                                         v3e[1],
                                         v3e[2],
                                         &tol[0],
                                         &tol[1],
                                         &tol[2]);
}

/**
 * \brief Per-axis domain tolerances for an edge-edge query.
 *
 * Written directly from TightInclusion's compute_edge_edge_tolerances rather
 * than generated: the previous SymPy form produced the same value for tol0 and
 * tol1, but TightInclusion's three axes use three different groupings of the
 * corner differences. Measured against TightInclusion over random queries, the
 * old tol1 and tol2 were off by factors of up to 2.5x and 6.9x, which let boxes
 * be accepted before they were tight enough along u and v.
 *
 * Each tolerance is the codomain tolerance divided by three times the largest
 * change of the difference vector along that axis, measured in the infinity
 * norm, then capped as clamp_div does.
 *
 * (v0s, v1s) are the first edge at t0 and (v2s, v3s) the second; the *e
 * arguments are the same points at t1.
 */
template <typename T>
static inline void compute_edge_edge_tolerance_soa(const T codomain_tol,
                                                   const T v0sx, const T v0sy, const T v0sz,
                                                   const T v1sx, const T v1sy, const T v1sz,
                                                   const T v2sx, const T v2sy, const T v2sz,
                                                   const T v3sx, const T v3sy, const T v3sz,
                                                   const T v0ex, const T v0ey, const T v0ez,
                                                   const T v1ex, const T v1ey, const T v1ez,
                                                   const T v2ex, const T v2ey, const T v2ez,
                                                   const T v3ex, const T v3ey, const T v3ez,
                                                   T* const SCCD_RESTRICT tol0,
                                                   T* const SCCD_RESTRICT tol1,
                                                   T* const SCCD_RESTRICT tol2) {
    // Corners of the (t, u, v) cube mapped through the difference function,
    // named as in TightInclusion: p<t><u><v>.
    const T p000[3] = {v0sx - v2sx, v0sy - v2sy, v0sz - v2sz};
    const T p001[3] = {v0sx - v3sx, v0sy - v3sy, v0sz - v3sz};
    const T p010[3] = {v1sx - v2sx, v1sy - v2sy, v1sz - v2sz};
    const T p011[3] = {v1sx - v3sx, v1sy - v3sy, v1sz - v3sz};
    const T p100[3] = {v0ex - v2ex, v0ey - v2ey, v0ez - v2ez};
    const T p101[3] = {v0ex - v3ex, v0ey - v3ey, v0ez - v3ez};
    const T p110[3] = {v1ex - v2ex, v1ey - v2ey, v1ez - v2ez};
    const T p111[3] = {v1ex - v3ex, v1ey - v3ey, v1ez - v3ez};

    auto linf_diff = [](const T a[3], const T b[3]) {
        return sccd::max<T>(sccd::abs<T>(b[0] - a[0]),
                            sccd::max<T>(sccd::abs<T>(b[1] - a[1]), sccd::abs<T>(b[2] - a[2])));
    };
    auto max_linf_4 = [&](const T a0[3], const T a1[3], const T a2[3], const T a3[3],
                          const T b0[3], const T b1[3], const T b2[3], const T b3[3]) {
        return sccd::max<T>(sccd::max<T>(linf_diff(a0, b0), linf_diff(a1, b1)),
                            sccd::max<T>(linf_diff(a2, b2), linf_diff(a3, b3)));
    };

    const T dl = T(3) * max_linf_4(p000, p001, p011, p010, p100, p101, p111, p110);
    const T edge0_length = T(3) * max_linf_4(p000, p100, p101, p001, p010, p110, p111, p011);
    const T edge1_length = T(3) * max_linf_4(p000, p100, p110, p010, p001, p101, p111, p011);

    *tol0 = sccd::clamp_domain_tol<T>(codomain_tol / dl, T(SCCD_MAX_TIME_TOL));
    *tol1 = sccd::clamp_domain_tol<T>(codomain_tol / edge0_length, T(SCCD_MAX_COORD_TOL));
    *tol2 = sccd::clamp_domain_tol<T>(codomain_tol / edge1_length, T(SCCD_MAX_COORD_TOL));
}

template <typename T>
static inline void compute_edge_edge_tolerance(const T codomain_tol,
                                               const T v0s[3],
                                               const T v1s[3],
                                               const T v2s[3],
                                               const T v3s[3],
                                               const T v0e[3],
                                               const T v1e[3],
                                               const T v2e[3],
                                               const T v3e[3],
                                               T* const SCCD_RESTRICT tol) {
    compute_edge_edge_tolerance_soa<T>(codomain_tol,
                                       v0s[0],
                                       v0s[1],
                                       v0s[2],
                                       v1s[0],
                                       v1s[1],
                                       v1s[2],
                                       v2s[0],
                                       v2s[1],
                                       v2s[2],
                                       v3s[0],
                                       v3s[1],
                                       v3s[2],
                                       v0e[0],
                                       v0e[1],
                                       v0e[2],
                                       v1e[0],
                                       v1e[1],
                                       v1e[2],
                                       v2e[0],
                                       v2e[1],
                                       v2e[2],
                                       v3e[0],
                                       v3e[1],
                                       v3e[2],
                                       &tol[0],
                                       &tol[1],
                                       &tol[2]);
}

SCCD_FP_STRICT_END

}  // namespace sccd

#endif
