/* Generated by SymPy; requires <limits> */
template <typename T>
static inline void sccd_get_numerical_error_vf_soa(
    const int use_ms,
    const T v0sx,
    const T v0sy,
    const T v0sz,
    const T v1sx,
    const T v1sy,
    const T v1sz,
    const T v2sx,
    const T v2sy,
    const T v2sz,
    const T v3sx,
    const T v3sy,
    const T v3sz,
    const T v0ex,
    const T v0ey,
    const T v0ez,
    const T v1ex,
    const T v1ey,
    const T v1ez,
    const T v2ex,
    const T v2ey,
    const T v2ez,
    const T v3ex,
    const T v3ey,
    const T v3ez,
    T* const SCCD_RESTRICT errx,
    T* const SCCD_RESTRICT erry,
    T* const SCCD_RESTRICT errz)
{
    const T kFilter =
        (use_ms ? T(34) : T(30)) * std::numeric_limits<T>::epsilon();
    *errx = sccd::pow3<T>(sccd::max<T>(
                sccd::max<T>(
                    sccd::max<T>(
                        sccd::max<T>(
                            sccd::max<T>(
                                sccd::max<T>(
                                    sccd::max<T>(
                                        sccd::max<T>(1, sccd::abs<T>(v0ex)),
                                        sccd::abs<T>(v0sx)),
                                    sccd::abs<T>(v1ex)),
                                sccd::abs<T>(v1sx)),
                            sccd::abs<T>(v2ex)),
                        sccd::abs<T>(v2sx)),
                    sccd::abs<T>(v3ex)),
                sccd::abs<T>(v3sx)))
        * kFilter;
    *erry = sccd::pow3<T>(sccd::max<T>(
                sccd::max<T>(
                    sccd::max<T>(
                        sccd::max<T>(
                            sccd::max<T>(
                                sccd::max<T>(
                                    sccd::max<T>(
                                        sccd::max<T>(1, sccd::abs<T>(v0ey)),
                                        sccd::abs<T>(v0sy)),
                                    sccd::abs<T>(v1ey)),
                                sccd::abs<T>(v1sy)),
                            sccd::abs<T>(v2ey)),
                        sccd::abs<T>(v2sy)),
                    sccd::abs<T>(v3ey)),
                sccd::abs<T>(v3sy)))
        * kFilter;
    *errz = sccd::pow3<T>(sccd::max<T>(
                sccd::max<T>(
                    sccd::max<T>(
                        sccd::max<T>(
                            sccd::max<T>(
                                sccd::max<T>(
                                    sccd::max<T>(
                                        sccd::max<T>(1, sccd::abs<T>(v0ez)),
                                        sccd::abs<T>(v0sz)),
                                    sccd::abs<T>(v1ez)),
                                sccd::abs<T>(v1sz)),
                            sccd::abs<T>(v2ez)),
                        sccd::abs<T>(v2sz)),
                    sccd::abs<T>(v3ez)),
                sccd::abs<T>(v3sz)))
        * kFilter;
}

template <typename T>
static inline void sccd_get_numerical_error_ee_soa(
    const int use_ms,
    const T v0sx,
    const T v0sy,
    const T v0sz,
    const T v1sx,
    const T v1sy,
    const T v1sz,
    const T v2sx,
    const T v2sy,
    const T v2sz,
    const T v3sx,
    const T v3sy,
    const T v3sz,
    const T v0ex,
    const T v0ey,
    const T v0ez,
    const T v1ex,
    const T v1ey,
    const T v1ez,
    const T v2ex,
    const T v2ey,
    const T v2ez,
    const T v3ex,
    const T v3ey,
    const T v3ez,
    T* const SCCD_RESTRICT errx,
    T* const SCCD_RESTRICT erry,
    T* const SCCD_RESTRICT errz)
{
    const T kFilter =
        (use_ms ? T(32) : T(28)) * std::numeric_limits<T>::epsilon();
    *errx = sccd::pow3<T>(sccd::max<T>(
                sccd::max<T>(
                    sccd::max<T>(
                        sccd::max<T>(
                            sccd::max<T>(
                                sccd::max<T>(
                                    sccd::max<T>(
                                        sccd::max<T>(1, sccd::abs<T>(v0ex)),
                                        sccd::abs<T>(v0sx)),
                                    sccd::abs<T>(v1ex)),
                                sccd::abs<T>(v1sx)),
                            sccd::abs<T>(v2ex)),
                        sccd::abs<T>(v2sx)),
                    sccd::abs<T>(v3ex)),
                sccd::abs<T>(v3sx)))
        * kFilter;
    *erry = sccd::pow3<T>(sccd::max<T>(
                sccd::max<T>(
                    sccd::max<T>(
                        sccd::max<T>(
                            sccd::max<T>(
                                sccd::max<T>(
                                    sccd::max<T>(
                                        sccd::max<T>(1, sccd::abs<T>(v0ey)),
                                        sccd::abs<T>(v0sy)),
                                    sccd::abs<T>(v1ey)),
                                sccd::abs<T>(v1sy)),
                            sccd::abs<T>(v2ey)),
                        sccd::abs<T>(v2sy)),
                    sccd::abs<T>(v3ey)),
                sccd::abs<T>(v3sy)))
        * kFilter;
    *errz = sccd::pow3<T>(sccd::max<T>(
                sccd::max<T>(
                    sccd::max<T>(
                        sccd::max<T>(
                            sccd::max<T>(
                                sccd::max<T>(
                                    sccd::max<T>(
                                        sccd::max<T>(1, sccd::abs<T>(v0ez)),
                                        sccd::abs<T>(v0sz)),
                                    sccd::abs<T>(v1ez)),
                                sccd::abs<T>(v1sz)),
                            sccd::abs<T>(v2ez)),
                        sccd::abs<T>(v2sz)),
                    sccd::abs<T>(v3ez)),
                sccd::abs<T>(v3sz)))
        * kFilter;
}
