option(SCCD_ENABLE_TBB "Use TBB for parallelization" OFF)
option(SCCD_ENABLE_OPENMP "Use OpenMP for parallelization" OFF)
option(SCCD_ENABLE_HACKS "Do not use without Scalable-CCD library" OFF)
option(SCCD_ENABLE_SMESH "Enable smesh and demos" OFF)
option(SCCD_ENABLE_TIGHT_INCLUSION "Enable Tight Inclusion" OFF)
